In [1]:
print("sdfghjk")

sdfghjk

In [2]:
!pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.4.6)
Requirement already satisfied: matplotlib in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\gaikw\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\gaikw\AppData\Roaming\Python\Python311\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\gaikw\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
!pip install seaborn

Requirement already satisfied: seaborn in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\gaikw\AppData\Roaming\Python\Python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\gaikw\AppData\Roaming\Python\Python311\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\gaikw\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\gaikw\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from scipy.stats import skew, kurtosis

np.random.seed(42)

regular_sales = np.random.normal(loc=5000, scale = 1200 , size = 95)
outliers = np.array([12000,13500,14000,800,500])

sales_data = np.concatenate([regular_sales,outliers])
df = pd.DataFrame(sales_data,columns=["sales"])

display(df.head())
display(df.describe())

         sales
0  5596.056984
1  4834.082839
2  5777.226246
3  6827.635828
4  4719.015950

              sales
count    100.000000
mean    5047.013936
std     1895.404027
min      500.000000
25%     4264.928123
50%     4847.652450
75%     5671.806926
max    14000.000000